sonar.projectKey=ecommerce
sonar.projectName=ecommerce
sonar.sources=frontend/src,backend
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.test.*
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Explicitly include JS and JSX files
sonar.inclusions=**/*.js,**/*.jsx,**/*.mjs
